### ISSUE TITLE
Play 3.0 support

### ISSUE THREAD

**Issue by matmannion** [play-swagger/play-swagger#47]
Play 3.0 changes the groupId from `com.typesafe.play` to `org.playframework` and replaces use of Akka with Pekko, a drop-in open source replacement.

Migration details here: https://www.playframework.com/documentation/3.0.x/Migration30

**Comment by Javakky-pxv** [comment]
@matmannion 
Thank you for your PR! I apologize for the delayed response.
We have released a Play 3.0 compatible version as play-swagger 2.0.x.
As my project has not yet utilized Play 3.0, I would appreciate it if you could inform me of any issues or problems during operation through Issues, PRs, etc.
(We have also already supported Play 2.9 in the 1.7.x version.)
